//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENT_DIALOG               102
#define IDD_CLIENT_LoginDlg             102
#define IDD_DIALOG_Message              103
#define IDD_MUSIC_DIALOG                104
#define IDD_MY_DIALOG                   105
#define IDD_DIALOG_TIP                  106
#define IDD_DIALOG1                     108
#define IDD_STATICCALENDAR_DIALOG       109
#define IDR_MAINFRAME                   128
#define IDD_CLIENT_RegisterDlg          129
#define IDB_BITMAP_ReOff                139
#define IDB_BITMAP_ReOn                 140
#define IDB_BITMAP_Log1                 150
#define IDB_BITMAP_Log2                 151
#define IDB_BITMAP_Log3                 152
#define IDB_BITMAP_Clientbg             153
#define IDB_BITMAP_Re1                  154
#define IDB_BITMAP_Re2                  155
#define IDB_BITMAP_Re3                  156
#define IDB_BITMAP_Close1               157
#define IDB_BITMAP_Close2               158
#define IDB_BITMAP_Close3               159
#define IDB_BITMAP_ReDlgbg              162
#define IDB_BITMAP_ReDlgClose           163
#define IDD_DIARY_DIALOG                164
#define IDB_BITMAP1                     166
#define IDD_DIALOG_MAIN                 169
#define IDD_CLIENT_Safety               170
#define IDD_CLIENT_INFO                 171
#define IDR_WAVE1                       172
#define IDR_WAVE2                       173
#define IDR_WAVE3                       174
#define IDB_BITMAP_MainDlgbg            175
#define IDB_BITMAP_Main_Note2           176
#define IDB_BITMAP_Main_Note3           177
#define IDB_BITMAP_Main_Note1           178
#define IDB_BITMAP_Main_Close1          179
#define IDB_BITMAP_Main_Close2          180
#define IDB_BITMAP_Main_Close3          181
#define IDB_BITMAP_Main_Diary1          182
#define IDB_BITMAP_Main_Diary2          183
#define IDB_BITMAP_Main_Diary3          184
#define IDB_BITMAP_Main_Set1            185
#define IDB_BITMAP_Main_Set2            186
#define IDB_BITMAP_Main_Set3            187
#define IDD_DIALOG_Setting              188
#define IDB_BITMAP_SIGNAL               189
#define IDB_BITMAP_Diarybg              190
#define IDB_BITMAP_Diary_Save1          192
#define IDB_BITMAP_Diary_Save2          193
#define IDB_BITMAP_Diary_Open1          194
#define IDB_BITMAP_Diary_Open2          195
#define IDB_BITMAP_Diary_Close1         196
#define IDB_BITMAP_Diary_Close2         198
#define IDB_BITMAP_Setbg                199
#define IDB_BITMAP_Set_perS1            200
#define IDB_BITMAP_Set_perS2            201
#define IDB_BITMAP_Set_Safe1            202
#define IDB_BITMAP_Set_Safe2            203
#define IDB_BITMAP_Set_perD1            204
#define IDB_BITMAP_Set_perD2            205
#define IDB_BITMAP_Musicbg              206
#define IDB_BITMAP_Musicplay            207
#define IDB_BITMAP_Musicpause           208
#define IDB_BITMAP_Musicadd             209
#define IDB_BITMAP_MusicSingle          211
#define IDB_BITMAP_MusicOrder           212
#define IDB_BITMAP_MusicRandom          213
#define IDB_BITMAP_Notebg               214
#define IDB_BITMAP_NoteDelete1          215
#define IDB_BITMAP_NoteDelete2          216
#define IDB_BITMAP_NoteSave1            217
#define IDB_BITMAP_NoteSave2            218
#define IDB_BITMAP_Infobg               220
#define IDB_BITMAP_safebg               221
#define IDB_BITMAP_Cal                  222
#define IDB_BITMAP_WhiteBrush           223
#define IDB_BITMAP_Calbg                224
#define IDB_BITMAP_Calz1                225
#define IDB_BITMAP_Calz2                226
#define IDB_BITMAP_Calzz1               227
#define IDB_BITMAP_Calzz2               228
#define IDB_BITMAP_Caly1                229
#define IDB_BITMAP_Caly2                230
#define IDB_BITMAP_Calyy1               231
#define IDB_BITMAP_Calyy2               232
#define IDB_BITMAP_CalClose1            233
#define IDB_BITMAP_CalClose2            234
#define IDB_BITMAP_CalStyle1            235
#define IDB_BITMAP_CalStyle2            236
#define IDB_BITMAP_Tipbg                239
#define IDB_BITMAP_Tip_Close1           240
#define IDB_BITMAP_Tip_Close2           241
#define IDB_BITMAP_Tip_Dtip1            242
#define IDB_BITMAP_Tip_Dtip2            243
#define IDB_BITMAP_Tip_OK1              244
#define IDB_BITMAP_Tip_OK2              245
#define IDB_BITMAP_Sunday2              246
#define IDB_BITMAP_Sunday1              247
#define IDB_BITMAP_MainMini1            248
#define IDB_BITMAP_MainMini2            249
#define IDB_BITMAP_MainMini3            250
#define IDR_WAVE4                       252
#define IDB_BITMAP_Kid1                 253
#define IDB_BITMAP_Kid2                 254
#define IDB_BITMAP_Kid3                 255
#define IDB_BITMAP_Diarybg1             256
#define IDB_BITMAP_Diarybg2             257
#define IDB_BITMAP_Diarybg3             259
#define IDB_BITMAP_ReAdminC1            260
#define IDB_BITMAP_ReAdminC2            262
#define IDB_BITMAP_ReAdminC3            263
#define IDC_EDIT_Admin                  1000
#define IDC_CALENDAR                    1000
#define IDC_EDIT_Pwd                    1001
#define IDC_EDIT_TIP                    1001
#define IDC_EDIT_YEAR                   1001
#define IDC_BUTTON_Log                  1002
#define IDC_DATETIMEPICKER_DATE         1002
#define IDC_EDIT_MONTH                  1002
#define IDC_BUTTON_Register             1003
#define IDC_EDIT_DAY                    1003
#define IDC_DATETIMEPICKER1             1003
#define IDC_EDIT_NewAdmin               1004
#define IDC_BUTTON_JOURNAL              1004
#define IDC_CHECK1                      1004
#define IDC_CHECK_SETALARM              1004
#define IDC_EDIT_PwdSet                 1005
#define IDC_SLIDER_Volume               1005
#define IDC_BUTTON_SAVE                 1005
#define IDC_BUTTON_NOTE                 1005
#define IDC_BUTTON1                     1005
#define IDC_EDIT_PwdSure                1006
#define IDC_COMBO_MusicList             1006
#define IDC_COMBO_HOUR                  1006
#define IDC_BUTTON_BIRTH                1006
#define IDC_BUTTON2                     1006
#define IDC_BUTTON_AdminCheck           1007
#define IDC_BUTTON_Play                 1007
#define IDC_COMBO_MINUTE                1007
#define IDC_BUTTON3                     1007
#define IDC_BUTTON_Pause                1008
#define IDC_LIST_TIP                    1008
#define IDC_BUTTON4                     1008
#define IDC_BUTTON_Mode                 1009
#define IDC_BUTTON_DELETE               1009
#define IDC_BUTTON5                     1009
#define IDC_BUTTON_Close                1011
#define IDC_EDIT_LASTMINUTE             1014
#define IDC_BUTTON_OK                   1016
#define IDC_Close                       1017
#define IDC_EDIT_TIME                   1017
#define IDC_EDIT_TEXT                   1018
#define IDC_BUTTON_SHUT                 1018
#define IDC_EDIT_HEAD                   1019
#define IDC_EDIT_REGULARTIP             1019
#define IDC_COMBO_Date                  1020
#define IDC_CHECK_OPEN                  1020
#define IDC_BUTTON_Weather              1021
#define IDC_BUTTON_Memorandum           1024
#define IDC_BUTTON_Diary                1025
#define IDC_BUTTON_SD                   1025
#define IDC_BUTTON_Setting              1026
#define IDC_BUTTON_EXIT                 1026
#define IDC_BUTTON_Calendar             1027
#define IDC_EDIT1                       1030
#define IDC_EDIT_FIRST                  1030
#define IDC_EDIT2                       1031
#define IDC_EDIT_SECOND                 1031
#define IDC_EDIT3                       1032
#define IDC_EDIT_NICKNAME               1032
#define IDC_EDIT_THIRD                  1032
#define IDC_EDIT4                       1033
#define IDC_EDIT_BIRTHDAY               1033
#define IDC_EDIT5                       1034
#define IDC_EDIT_HABIT                  1034
#define IDC_COMBO1                      1035
#define IDC_EDIT6                       1035
#define IDC_EDITCONSTELLATION           1035
#define IDC_COMBO_FONT                  1035
#define IDC_EDIT7                       1036
#define IDC_EDIT_WEIGHT                 1036
#define IDC_EDIT8                       1037
#define IDC_EDIT_HEIGHT                 1037
#define IDC_Button_MainClose            1038
#define IDC_BUTTON_MUSIC                1039
#define IDC_BUTTON_Safety               1040
#define IDC_STATIC_Motto                1040
#define IDC_BUTTON_INFO                 1041
#define IDC_STATIC_GREET                1041
#define IDC_BUTTON_SetClose             1042
#define IDC_STATIC_TIP                  1043
#define IDC_BUTTON6                     1045
#define IDC_BUTTON_TipClose             1046
#define IDC_BUTTON_MINI                 1047
#define IDC_STATIC_Holiday              1050
#define IDC_STATIC_THE                  1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
